#!/usr/bin/env bash
# One-time WireGuard server install, native on the host (NOT a container).
# Native so the tunnel keeps working when Docker is down -- it is the path
# you use to SSH in and fix Docker. The kernel module ships with Ubuntu; this
# only adds the userspace tools, one config file and a systemd unit.
#
#   sudo bash /mnt/calculon/media-stack/wireguard-install.sh
#
# Afterwards add devices with:  sudo ./wg-peer.sh add <name>
# Re-running is safe: existing keys and config are kept.
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "Run me with sudo."; exit 1; }

WG_IF=wg0
WG_PORT=51820                 # forward UDP $WG_PORT on the gateway -> this host
WG_SUBNET=10.13.13.0/24       # tunnel addresses; must not overlap the LAN,
WG_SERVER_IP=10.13.13.1       # docker (172.17/172.28) or a typical hotel LAN
WAN_IF=$(ip -4 route show default | awk '{print $5; exit}')
[ -n "$WAN_IF" ] || { echo "cannot find the default-route interface" >&2; exit 1; }

CONF=/etc/wireguard/$WG_IF.conf

echo "== 1. packages =="
apt-get update -qq
apt-get install -y -qq wireguard-tools qrencode

echo "== 2. server config ($CONF) =="
umask 077
mkdir -p /etc/wireguard/peers
if [ -f "$CONF" ]; then
  echo "   keeping existing $CONF"
else
  PRIV=$(wg genkey)
  cat > "$CONF" <<WG
# WireGuard server -- generated by wireguard-install.sh $(date -I)
# Peers are appended below by wg-peer.sh; do not hand-edit while it is running,
# or run 'wg syncconf $WG_IF <(wg-quick strip $WG_IF)' afterwards.
[Interface]
Address    = $WG_SERVER_IP/${WG_SUBNET#*/}
ListenPort = $WG_PORT
PrivateKey = $PRIV
# NAT tunnel traffic out of $WAN_IF so LAN devices (which have no route back
# to $WG_SUBNET) can reply. Forwarding itself is permitted by ufw
# ('ufw route allow in on $WG_IF', added by the installer).
PostUp   = iptables -t nat -A POSTROUTING -s $WG_SUBNET -o $WAN_IF -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s $WG_SUBNET -o $WAN_IF -j MASQUERADE
WG
  echo "   wrote $CONF (server public key: $(wg pubkey <<<"$PRIV"))"
fi

echo "== 3. IP forwarding (Docker already sets it at runtime; make it survive without Docker) =="
cat > /etc/sysctl.d/99-wireguard.conf <<'SYS'
net.ipv4.ip_forward = 1
SYS
sysctl -q -p /etc/sysctl.d/99-wireguard.conf

echo "== 4. ufw =="
if command -v ufw >/dev/null && ufw status | grep -q '^Status: active'; then
  # The listener itself, from anywhere (WireGuard silently drops anything that
  # is not a valid handshake, so an open UDP port reveals nothing).
  ufw allow "$WG_PORT/udp" comment 'wireguard'
  # Tunnel clients are trusted like the LAN: they may reach this host (SSH,
  # Jellyfin :8096) and be forwarded on (published container ports, other LAN
  # devices, and the internet for --full peers).
  ufw allow in on "$WG_IF" comment 'wireguard clients -> host'
  ufw route allow in on "$WG_IF" comment 'wireguard clients -> LAN/internet'
else
  echo "   ufw not active -- nothing to open"
fi

echo "== 5. enable + start =="
systemctl enable --now "wg-quick@$WG_IF"
wg show "$WG_IF"

cat <<EOT

DONE. Two things left:

  1. Forward UDP $WG_PORT on the gateway (http://192.168.1.254 -> Firewall ->
     NAT/Gaming): add a custom service 'WireGuard', global port $WG_PORT-$WG_PORT,
     base host port $WG_PORT, protocol UDP, then assign it to this host
     (192.168.1.64). Same two-stage dance as the Caddy 80/443 forwards.

  2. Add a device:   sudo $(dirname "$(readlink -f "$0")")/wg-peer.sh add <name>
     It prints a QR code for the phone app, or a .conf for desktop clients.
EOT
